baseURL = "https://gerbenzaagsma.github.io/dh-histories/"
title = "Histories of Digital Humanities"
languageCode = "en"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[taxonomies]
tag = "tags"
category = "categories"

[params]
  brand = "Histories of Digital Humanities"
  description = "News, events, and projects."

[markup]
  [markup.goldmark.renderer]
    unsafe = true