baseURL = "https://gerbenzaagsma.github.io/dh-histories/"
title = "Histories of Digital Humanities"
languageCode = "en"
theme = "mainroad"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[taxonomies]
tag = "tags"
category = "categories"

[params]
  subtitle = "Digital Histories"
  description = "News, events, and projects"
  author = "Gerben Zaagsma"

  [params.style.vars]
    highlightColor = "#e22d30"   # accent color

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"

   # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]


[markup]
  [markup.goldmark.renderer]
    unsafe = true


[menu]
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 10

  [[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 20

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 30

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 40